### PR TITLE
Revamp

### PR DESCRIPTION
**Pull request by TBK**
This PR changes a lot. I did the work yesterday so I have not had the chance to do extensive testing so feedback/testing is appreciated.

Short description:
- Restructures the source tree
- Simplifies and updates the Dockerfile and docker-compose.yml file
- Typo fixes, restructure and update README.md
- Improved the scripts based on shellcheck recommendations

### CODE REVIEW

**Comment by TBK** [comment]
Should resolve https://github.com/alinmear/docker-conanexiles/issues/20

**Comment by tmzasz** [comment]
ae1449a
thats some FHS goodness right there

**Comment by TBK** [comment]
FHS = Filesystem Hierarchy Standard?

**Comment by tmzasz** [comment]
yes

**Comment by alinmear** [comment]
Is this PR save to merge?

**Comment by TBK** [comment]
I just checked. The only change I had done was to update Redis to v5 which I have just added to the PR.

Otherwise I have been running it in production since I made the PR (Oct 21) without issues.

**Comment by TBK** [comment]
When Wine 4 hits release the base Ubuntu image should be bumped to 18.10.

**Comment by alinmear** [comment]
Thx for your work. Merged!

**Pull request merged**
